Вариант 16


In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з найменшими непарними числами, не менше 15, та виведіть його значення.

In [2]:
a = 15
array = np.arange(1, a * 2, 2)
print(array)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями суми перших n натуральних чисел для кожного n, починаючи з 1, та виведіть його значення

In [8]:
a = np.zeros((3, 3), dtype=int)

for i in range(3):
    for j in range(3):
        n = i * 3 + j + 1
        a[i, j] = n * (n + 1) // 2

print(a)

[[ 1  3  6]
 [10 15 21]
 [28 36 45]]


3.	Створіть масив розміром 7x7, заповніть його випадковими дійсними числами від 0 до 1 та знайдіть середнє геометричне його елементів.

In [6]:
a = np.random.uniform(0, 2, (7,7))
geometric_mean = np.prod(a) ** (1 / a.size)

print("Матриця:")
print(a)
print("Середнє геометричне:", geometric_mean)

Матриця:
[[1.09391289 0.28324745 0.82025946 1.50735101 0.40530848 1.9894306
  0.0996136 ]
 [0.52258234 0.04815172 1.42379125 0.83009501 1.98179974 1.8013577
  0.9613652 ]
 [1.38883391 0.08302788 1.94975259 1.51807612 1.04429412 1.33062976
  1.92117559]
 [0.73699583 0.98615491 0.61219654 1.8969791  1.27082712 0.80892829
  1.64977222]
 [0.58998114 1.91385024 0.27341632 0.47531514 0.78924435 0.36909594
  0.68405312]
 [1.1083731  1.43693439 0.04963926 1.3465955  1.63648442 1.92721672
  0.87994968]
 [1.68313889 0.0044651  1.04147234 0.00525978 0.80748826 0.9050702
  0.1498918 ]]
Середнє геометричне: 0.6310479679565348



4.	Створіть масив розміром 6x6, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить мінімальні елементи в кожному рядку.



In [7]:
a = np.random.rand(6, 6)

min = np.min(a, axis=1)
min_col = min.reshape(-1, 1)
print("Матриця:")
print(a)
print("Вектор-стовпчик з мінімальними елементами в кожному рядку:")
print(min_col)

Матриця:
[[0.96607046 0.03197791 0.02458686 0.05881213 0.28347315 0.03943811]
 [0.43882827 0.94113149 0.60052971 0.26895963 0.79923137 0.35052487]
 [0.33153069 0.08411947 0.09960754 0.51202951 0.30524445 0.39887532]
 [0.15024997 0.27659819 0.58348914 0.53232892 0.47407138 0.2381664 ]
 [0.14169869 0.18096501 0.87926165 0.12947564 0.89748627 0.60000793]
 [0.46106392 0.03447558 0.49971253 0.0283655  0.68546856 0.23709726]]
Вектор-стовпчик з мінімальними елементами в кожному рядку:
[[0.02458686]
 [0.26895963]
 [0.08411947]
 [0.15024997]
 [0.12947564]
 [0.0283655 ]]


5. 	Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими числами від -5 до 5 та виконайте на них поелементні операції додавання, віднімання та множення.

In [9]:
a = np.random.randint(-5, 6, size=4)
b = np.random.randint(-5, 6, size=4)

print("a = ", a)
print("b = ", b)

print("a + b = ", a + b)
print("a - b = ", a - b)
print("a * b = ", a * b)

a =  [-1  3  4 -3]
b =  [-4 -2 -1 -1]
a + b =  [-5  1  3 -4]
a - b =  [ 3  5  5 -2]
a * b =  [ 4 -6 -4  3]


6:.	Створіть два вектори розміром 4, заповніть їх довільними дійсними числами та знайдіть їх скалярний добуток.

In [10]:
a = np.random.uniform(1, 11, 4)
b = np.random.uniform(1, 11, 4)

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Скалярний добуток векторів дорівнює:", dot_a_b)

a =  [7.71856846 4.01588742 3.49894609 8.0510981 ]
b =  [ 7.86939906  1.27108983  7.01746767 10.22932225]
Скалярний добуток векторів дорівнює: 172.75606707338653


7. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 12 та перемножте їх між собою.

In [12]:
a = np.random.randint(1, 12, size=(2, 3))
b = np.random.randint(1, 12, size=(3, 3))

dot_a_b = np.dot(a, b)

print("a = ", a)
print("b = ", b)
print("Результат множення матриць:")
print(dot_a_b)

a =  [[ 8  7  1]
 [ 5 11  8]]
b =  [[ 3  5  9]
 [ 3  7  6]
 [ 3 10 10]]
Результат множення матриць:
[[ 48  99 124]
 [ 72 182 191]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю

In [13]:
a = np.random.randint(1, 13, size=(3, 3))
print("Вихідна матриця:")
print(a)

if np.linalg.det(a) == 0:
    print("Матриця не має оберненої матриці.")
else:
    inv_a = np.linalg.inv(a)
    print("Обернена матриця:")
    print(inv_a)

Вихідна матриця:
[[ 4  3 10]
 [ 6 10  9]
 [ 6  4 12]]
Обернена матриця:
[[-1.07692308 -0.05128205  0.93589744]
 [ 0.23076923  0.15384615 -0.30769231]
 [ 0.46153846 -0.02564103 -0.28205128]]


9.	Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від -7 до 7 та транспонуйте її.

In [15]:
a = np.random.uniform(-7, 7,(4, 4))
print(a)

a_transp = np.transpose(a)
print("Транспонована матриця:")
print(a_transp)

[[ 0.53881122  1.53649666 -5.70439184  5.821409  ]
 [ 1.66751084 -3.69573038  1.71089173  1.06336236]
 [ 4.90988473 -3.07763604  0.89006673 -6.39268456]
 [-1.25457869 -1.88123582 -5.20518174  0.24571686]]
Транспонована матриця:
[[ 0.53881122  1.66751084  4.90988473 -1.25457869]
 [ 1.53649666 -3.69573038 -3.07763604 -1.88123582]
 [-5.70439184  1.71089173  0.89006673 -5.20518174]
 [ 5.821409    1.06336236 -6.39268456  0.24571686]]


10.	Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть суму елементів отриманого вектору.

In [16]:
a = np.random.rand(3, 4)
b = np.random.rand(4)
sum = np.sum(b)

print("Матриця:")
print(a)
print("Вектор:")
print(b)
print("Сума елементів вектору:", sum)

Матриця:
[[0.27920712 0.99174451 0.45616939 0.4415957 ]
 [0.22172197 0.1728814  0.79604997 0.25540238]
 [0.72021118 0.41375941 0.60539078 0.37641095]]
Вектор:
[0.170153   0.66217528 0.97504133 0.56197724]
Сума елементів вектору: 2.3693468465653327


11.	Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор

In [18]:
matr = np.random.rand(2, 3)
vect = np.random.randint(1, 11, 3)
print("Матриця:")
print(matr)
print("Вектор:")
print(vect)

print("Результат множення матриці на вектор:")
result = np.dot(matr, vect)
print(result)

Матриця:
[[0.9455441  0.78803262 0.90303551]
 [0.73824652 0.43284456 0.31316288]]
Вектор:
[1 3 6]
Результат множення матриці на вектор:
[8.72785504 3.91575749]


12.	Створіть дві матриці розміром 9x9, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть відношення елементів другого стовпця другої матриці до відповідних елементів першої матриці (поелементне ділення).

In [19]:
a = np.random.randint(1, 11, (9, 9))
b = np.random.randint(1, 11, (9, 9))

print("Перша матриця:")
print(a[:, :3])
print("Друга матриця:")
print(b[:, :3])

result = b[:, 1] / a[:, 1]

print("Відношення елементів другого стовпця другої матриці до першої матриці:")
print(result)


Перша матриця:
[[ 1  7  4]
 [ 2  2  8]
 [ 8  4  7]
 [ 2 10  5]
 [ 1  5  7]
 [ 7 10  1]
 [ 5  6  6]
 [ 2  8  2]
 [ 5  2  9]]
Друга матриця:
[[ 1  3  9]
 [ 7 10  3]
 [ 5  9 10]
 [ 8 10  5]
 [ 1  5  1]
 [ 5  1  7]
 [ 4 10  4]
 [ 8  3  9]
 [ 2  7  6]]
Відношення елементів другого стовпця другої матриці до першої матриці:
[0.42857143 5.         2.25       1.         1.         0.1
 1.66666667 0.375      3.5       ]


13.	Створіть дві матриці розміром 8x8, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть добуток їх елементів.

In [2]:
a = np.random.randint(1, 11, size=(8, 8))
b = np.random.randint(1, 11, size=(8, 8))
print("Перша матриця:")
print(a)
print("Друга матриця:")
print(b)

print("Добуток матриць:")
result = np.dot(a, b)
print(result)

Перша матриця:
[[ 5  9  2  8  3  6  3  5]
 [ 7  3  4 10  5  9  2  5]
 [ 5  1  3  3  3 10  3 10]
 [ 3 10  7  4  1  9  4 10]
 [ 7  2  5 10  4  9  5  7]
 [ 2  3  9  4  4  8  1  5]
 [ 4  2  8  9  9  4  5 10]
 [10  6  2  3  9  4 10  9]]
Друга матриця:
[[ 4  2  3  3  2  7  3  4]
 [ 8  3  2  5  4  8 10  3]
 [ 6  6  1 10  2  3 10  9]
 [ 5  9  8  6  8  1 10  1]
 [ 8  5  3  6  7  6  7  2]
 [ 3  3  2  2  1  3  8  9]
 [ 8  4  8  2  7  6  1 10]
 [ 9  1  8  2  5  6  1  8]]
Добуток матриць:
[[255 171 184 174 187 205 282 203]
 [254 202 200 198 197 194 305 234]
 [229 125 177 132 146 181 199 259]
 [311 172 201 205 186 243 312 312]
 [286 214 236 207 219 213 303 284]
 [215 156 129 187 134 153 264 232]
 [339 230 251 248 256 233 312 287]
 [360 183 255 198 254 307 254 305]]


14.	Створіть матрицю розміром 8x8, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть середнє геометричне значення елементів матриці.

In [3]:
a = np.random.randint(1, 101, size=(8, 8))
print("Матриця:")
print(a)

geometric_avg = np.prod(a) ** (1 / a.size)

print("Середнє геометричне значення матриці", geometric_avg)


Матриця:
[[ 37  74 100  34  77   9  63  46]
 [ 83  84  21  70  66  65  53  84]
 [ 17  60  32  12  43  71  62  52]
 [ 61  11  89  51  31  54  13  39]
 [ 15  95  77  56  43   3  35  89]
 [ 70  65  76  10  76  17  46  79]
 [ 70  50  51  74  41  72  51  27]
 [  1  28  48  59  97  45  10  86]]
Середнє геометричне значення матриці 1.974575712008142


15.	Створіть матрицю розміром 10x10, заповніть її випадковими дійсними числами в діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить найменше за модулем ціле значення в кожному рядку матриці.

In [5]:
a = np.random.uniform(-2, 2, (10, 10))

print("Матриця:")
print(a)

min_abs_values = np.min(np.abs(a), axis=1)
min_index = np.argmin(np.abs(a), axis=1)

result = a[np.arange(10), min_index].reshape(-1, 1)

print("Вектор стовпчик з мінімальними за модулем ")
print(result)

Матриця:
[[-1.60781753 -0.10472663 -0.03610986  1.66867431 -1.64813356 -1.02519918
   0.04442062  1.18815925  1.11602157 -0.98627429]
 [ 0.73379802 -1.30694226  0.22838858 -0.59400922  1.3770598  -1.21871576
   1.73203776  0.36178859  1.19849627 -1.79713605]
 [-0.05600418 -1.67924406 -1.56830272  0.66018854 -1.78504892 -1.69347806
   0.38057843  1.26094195 -0.43358138  1.9889468 ]
 [ 1.24456204 -0.67606956  1.60812851 -1.83242008  0.86634213 -1.90609501
   1.5190396   1.15554566 -0.60365714  1.49391937]
 [-0.86760885 -1.76026356 -1.01429635 -1.57952184  0.675376    1.61811824
  -1.98818815  1.78179087  1.87492972 -1.7816637 ]
 [ 1.17837817 -0.68059657 -0.79826339 -1.12367432  0.93055313  0.29784648
  -1.65277449  0.58601706 -0.34026825  1.52940208]
 [-0.74430221 -1.96894423 -0.28990559  1.66968711  1.37634081 -1.95987487
   1.13190362  1.80001926  1.24496863  0.49259943]
 [-0.7289388  -1.46948098  1.54308081  0.88372626  0.83489915 -1.33620044
  -1.4237813   0.31673011  1.60599367  1.5

Висновок: В цій лабороторній роботі було виконано різні завдання з використанням бібліотеки numpy. Теми завдань включали розробку транспонованих матриць, поелементних операцій, створення матриць та векторів та обчислення середнього геометричного.